### ISSUE TITLE
Marked Settings

### ISSUE THREAD

**Issue by sangyoo91** [chuangbo/meteor-marked#17]
```
marked.setOptions({
  renderer: new marked.Renderer(),
  gfm: true,
  tables: true,
  breaks: false,
  pedantic: false,
  sanitize: true,
  smartLists: true,
  smartypants: false
});
```

how would I use this?

**Comment by chuangbo** [comment]
Have you tried put those on any client js file? I think it will just work because a window.marked always exists by default.

**Comment by gadicc** [comment]
@sangyoo91, any luck?  What are you trying where, what is happening, and what do you expect to happen? :)

**Comment by sangyoo91** [comment]
I just wasn't sure where to put this to use it. I will try putting it into any client js. I was asking if there was a proper way to do this. Or if its okay to put it anywhere.

**Comment by gadicc** [comment]
Yup, anywhere is good.  Client js is fine if you're not using marked on the server for anything.
