### ISSUE TITLE
How to create a subset parser?

### ISSUE THREAD

**Issue by fardeemmunir** [chuangbo/meteor-marked#18]
First of all, awesome work. Loving it.

I was wondering how to change the parser so the markdown links doesn't work. So []() wouldn't be interpreted as anchor links.

Thanks

**Comment by gadicc** [comment]
Hey @fardeemmunir, can you be a bit clearer about exactly what you mean?  Maybe with an example of some source text, how it is currently being parsed, and how you'd like it to be parsed.

In general though this package ("meteor-marked") is just a wrapper around the original [marked](https://github.com/chjj/marked), and you may have better luck on that repo.  Particularly the docs on the front page, which are a lot more detailed than the small example we have here.

**Comment by gadicc** [comment]
Any luck? :)

**Comment by fardeemmunir** [comment]
I go it. There was an issue filed on the marked repo explaining how to do
it. The gist is to make a `new marked.Renderer()` and then set some of the
properties such as heading etc to produce nothing special.

On Tue, Feb 24, 2015 at 9:19 PM, Gadi Cohen <notifications@github.com>
wrote:

> Any luck? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chuangbo/meteor-marked/issues/18#issuecomment-75775601>
> .
>



-- 
Fardeem Munir
www.erubai.com
@awesomerubai

**Comment by gadicc** [comment]
Ok great, thanks!
