### ISSUE TITLE
Use with highlight.js

### ISSUE THREAD

**Issue by sangyoo91** [chuangbo/meteor-marked#19]
I tried this in `Template.foo.rendered` 

```
	var marked = require('marked');

	// Synchronous highlighting with highlight.js
	marked.setOptions({
	  highlight: function (code) {
	    return require('highlight.js').highlightAuto(code).value;
	  }
	});
```

but it does not work. How would I use highlight.js with this?

I'm using

simple:highlight.js

with this package.

**Comment by efounders** [comment]
like this:

    marked.setOptions({
      highlight: function (code) { return hljs.highlightAuto(code).value; }
    });

**Comment by acemtp** [comment]
like this:

    marked.setOptions({
      highlight: function (code) { return hljs.highlightAuto(code).value; }
    });

**Comment by ctzurcanu** [comment]
this should be included in the README.md

**Comment by gadicc** [comment]
thanks, @acemtp for the example.

@ctzurcanu, that's a fair comment... done :)
